version: "3"
services:
  gd_ai:
    container_name: gd_ai
    build:
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    restart: unless-stopped
    networks:
      - gd


  gd_rabbitmq:
    hostname: rabbit
    container_name: gd_rabbitmq
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    depends_on:
      - gd_ai
    networks:
      - gd
    expose:
      - "15672"

  gd_celery:
    container_name: gd_celery
    build:
     dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - gd_ai
      - gd_rabbitmq
    networks:
      - gd
    command:
      [
        "celery",
        "-A",
        "tasks",
        "worker",
        "--loglevel=info",
        "--pool",
        "threads",
      ]

networks:
  gd:
    driver: bridge