version: "3"
services:
  gd_ai:
    container_name: gd_ai
    build:
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: gunicorn -w 2 -b 0:8000 wsgi:app
    restart: unless-stopped
    networks:
      - gd

  gd_nginx:
    container_name: gd_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - gd_ai
    networks:
      - gd


  gd_rabbitmq:
    hostname: rabbit
    container_name: gd_rabbitmq
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    depends_on:
      - gd_ai
    networks:
      - gd
    expose:
      - "15672"

  gd_celery:
    container_name: gd_celery
    build:
     dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - gd_ai
      - gd_rabbitmq
    networks:
      - gd
    command:
      [
        "celery",
        "-A",
        "tasks",
        "worker",
        "--loglevel=info",
        "--pool",
        "threads",
      ]

  redis:
    container_name: gd_ai_redis
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - gd

networks:
  gd:
    driver: bridge